name: Synchronize shared infrastructure

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
    - name: Checkout this repo
      uses: actions/checkout@v3

    - name: Move to the cloud
      run: cd ./cloud

    - name: Setup Terraform tooling
      uses: hashicorp/setup-terraform@v2

    - name: Ensure sensible code
      run: |
        terraform fmt -check
        terraform validate

    - name: Synchronize existing resources
      run: ./cloud.sh sync

    - name: Plan the upcoming change
      if: github.event_name == 'pull_request'
      run: terraform plan

    - name: Actually apply the change
      if: github.ref == 'refs/heads/main'
      run: terraform apply -auto-approve
