name: Update depended packages
on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:
jobs:
  stablearhtns:
    name: Check for broken evolutions
    runs-on: macos-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Install a flaked Nix
        uses: DeterminateSystems/nix-installer-action@v14
      - name: Update to the latest
        run: |
          nix flake update
      - name: Confirm darwin builds
        run: |
          nix build .#darwinConfigurations.ezmbp24.local.system
      - name: Save the flake locks
        uses: actions/cache/save@v4
        with:
          key: ${{ github.run_id }}
          path: flake.lock
  updateronimo:
    name: Snapshot upstream releases
    needs: stablearhtns
    runs-on: self-hosted
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Configure git credentials
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
      - name: Reflect existing Nix
        id: nixos
        continue-on-error: true
        run: uname -a | grep NixOS
      - name: Install a flaked Nix
        if: steps.nixos.outcome != 'success'
        uses: DeterminateSystems/nix-installer-action@v14
      - name: Cached the latest locks
        uses: actions/cache/restore@v4
        with:
          key: ${{ github.run_id }}
          path: flake.lock
      - name: Write remembered commit
        run: |
          cat flake.lock
      - name: Insure nixos builds
        run: |
          nix build .#nixosConfigurations.tom.config.system.build.toplevel
      - name: Save changed version
        run: |
          git diff
          # git commit --all --message "chore(deps): automatic version bump to the most recent packages"
          # git push -u origin main
